apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-app-config
  namespace: bank-app-namespace
data:
  MYSQL_DATABASE: BankDB
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-headless.bank-app-namespace.svc.cluster.local:3306/BankDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

