apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-app-deployment
  namespace: bank-app-namespace
  labels:
    app: bank-app
spec:
  selector:
    matchLabels:
      app: bank-app
  template:
    metadata:
      labels:
        app: bank-app
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.28
        command: ["/bin/sh", "-c", "until nc -z -v -w30 mysql-headless.bank-app-namespace.svc.cluster.local 3306; do echo 'Waiting for MySQL to start...'; sleep 5; done; echo 'MySQL is up and running!';"]
      containers:
      - name: bank-app
        image: banunirahul03/springboot_bankapp:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 600m
            memory: 512Mi
          limits:
            cpu: 800m
            memory: 1200Mi
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: bank-app-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: bank-app-config
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bank-app-secrets
              key: SPRING_DATASOURCE_PASSWORD
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
      tolerations:
      - key: "prod"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
