apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: bank-app-namespace
  labels:
    app: mysql
spec:
  clusterIP: None  # Creates a headless service
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
