apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-role-binding
  namespace: bank-app-namespace
subjects:
  - kind: User
    name: bank-user  # The user or service account
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: bank-ext-user  # Role to bind to the user
  apiGroup: rbac.authorization.k8s.io
