apiVersion: v1
kind: Service
metadata:
  name: bank-app-service
  namespace: bank-app-namespace
  labels:
    app: bank-app
spec:
  type: NodePort
  selector:
    app: bank-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
